### ISSUE TITLE
#shutdown

### ISSUE THREAD

**Issue by HstufAmir** [TheGamingChief/BattlEye-Extended-Controls#1]
hi when BEC use Shutdown command server stop working. how can i fix it?
pls help me

**Comment by TheGamingChief** [comment]
Hi @HstufAmir,

Just to verify you are saying the DayZ Server exe stops working when the shutdown command is issued?

If that is the case, are you running any mods on the server, if so which ones?

**Comment by HstufAmir** [comment]
> Hi @HstufAmir,
> 
> Just to verify you are saying the DayZ Server exe stops working when the shutdown command is issued?
> 
> If that is the case, are you running any mods on the server, if so which ones?

**Comment by HstufAmir** [comment]
hi i test without mods and with mods but dont work
