### ISSUE TITLE
[QUESTION] Is it okay to ask you DayZ related questions on here?

### ISSUE THREAD

**Issue by gaveitatry2** [TheGamingChief/BattlEye-Extended-Controls#2]
Would it be okay if I ask you some DayZ related questions in addition to BEC ones here?  Your YouTube tutorial videos don't seem to be a good place to ask the questions because mine often get ignored.  Also, comments on GitHub are easier to read and I can even do things like post screenshots and videos.  Please?

**Comment by TheGamingChief** [comment]
@idgas01 I would recommend asking me questions via Discord DM or via my Discord server as I don't check GitHub very often. 

Here's a link to my Discord: https://link.thegamingchief.com/Discord
Being on my Discord server automatically allows you to send me DM's without having to be friends on Discord.
