### ISSUE TITLE
'BEC installation Servers 

### ISSUE THREAD

**Issue by Theprof01** [TheGamingChief/BattlEye-Extended-Controls#3]
im downloading the version linked to the DayZ V2 Tcadmin following steps and trying to launch BEC getting the error config isnt there i did see ur mention that this was removed for servers then but this can manage to launch or config it then ?

**Comment by TheGamingChief** [comment]
Do you have a screenshot of the error you are getting @Theprof01 ? It sounds like maybe you don't have the config file in the right location or BEC is being started incorrectly.

**Comment by TheGamingChief** [comment]
I'll go ahead and close this issue due to inactivity.
