### ISSUE TITLE
Bec cannot connect to Dayz server 1.13

### ISSUE THREAD

**Issue by thrashlord777** [TheGamingChief/BattlEye-Extended-Controls#4]
Hey! I am trying to set up bec 1.608, on a Dayz 1.13 server (127.0.0.1, port 2302). After starting the Dayz server, I launch the bat file (code: 
cd "C:\OmegaManager\servers\DayzServer\bec\"
Bec.exe -f Config.cfg --dsc), the console window opens, waits for a timeout of 10 seconds, tries to connect and gives the error "No Valid response. Trying to reconnect.!". The path to BattlEye in Config.cfg is "DayzServer \ battleye \". Tried it through OmegaManager, the Bec waits for a timeout 30 sec and the Dayz server does not start until the bat file is executed, then it gives the error "Lost Connection! Closing socket & exiting!" and then the Dayz server starts up. What else can you try to do?
According to the instructions for 1.13, I created a folder in "profiles \ BattlEye", indicated the RCON port 2305. In the Bec config file, where to specify the path to BattlEye to the server root or profiles?

**Comment by thrashlord777** [comment]
I figured it out. In the BEC config, you need to specify the RCON port, in my case 2305 and calculate the time after how long the dayz server will be fully loaded, the "Job loaded" status. In this situation, everything is loaded, the scheduler is working, the auto-restart is working. Thank you.

**Comment by TheGamingChief** [comment]
Hi thrashlord777,

Sorry about the delayed response on this issue. I just wanted to comment here for anyone else who may see this, make sure your port is set to your RCon port and not the game port. Clarifying details and default values have been added to Config.cfg and pushed in the following commit.

https://github.com/TheGamingChief/BattlEye-Extended-Controls/commit/d6eb744f55b342ddea0de9f090577261c89a07a0

Thanks again for the report and the details regarding your resolution.

**Comment by SirTobil** [comment]
> I figured it out. In the BEC config, you need to specify the RCON port, in my case 2305 and calculate the time after how long the dayz server will be fully loaded, the "Job loaded" status. In this situation, everything is loaded, the scheduler is working, the auto-restart is working. Thank you.

Can you explain more about what you did to fix this? I am having the same issue it sounds like and I can't seem to get it working. I don't quite know how to add that 'calculated delay' or 'job loaded' that you mentioned. :/

**Comment by TheGamingChief** [comment]
@SirTobil ensure your BEC Config.cfg has the port set as your RCon port (default 2305) and not your game port (default 2302). For more details on setting an RCon port take a look at this video: https://youtu.be/_S7wzEe6Kwg

If you are still having issues I recommend joining my Discord (linked in that video) and we can look more into your issue.
