### ISSUE TITLE
BEC Connects to early.

### ISSUE THREAD

**Issue by Shal3R** [TheGamingChief/BattlEye-Extended-Controls#6]
Hi, today i installed my DayZ server with BEC. When i start Server its loading all the staf for about 15+ seconds and BEC Starts at the same time when i start the server but due to long Dayz server load BEC can't connect and shows:

17:45:41 : No Valid response. Trying to reconnect.!
﻿17:45:45 : No Valid response. Trying to reconnect.!
﻿17:45:49 : No Valid response. Trying to reconnect.!
﻿17:45:54 : Lost Connection!
﻿17:45:54 : Closing socket & exiting!

Then BEC closes.  And when DayZ server is loaded fully i can manualy open BEC and it connects without problems.

QUESTION: 
How to delay BEC so it make this connection for example 30 seconds later or how to increase time between reconnects cuz 4 seconds is not enough.

Thnaks.

**Comment by TheGamingChief** [comment]
@Shal3R Edit the "Timeout" in BattlEye-Extended-Controls/Config/Config.cfg to something higher. The value will depend on how long your server takes to start, but you want the timeout to finish shortly after the server loads.

**Comment by Shal3R** [comment]
> @Shal3R Edit the "Timeout" in BattlEye-Extended-Controls/Config/Config.cfg to something higher. The value will depend on how long your server takes to start, but you want the timeout to finish shortly after the server loads.

HOW CAN I CONTACT YOU ?

**Comment by TheGamingChief** [comment]
@Shal3R https://link.thegamingchief.com/discord
